command_timeout = 2000

[directory]
format = "[ ﱮ $path ]($style)"
style = "fg:bright-blue"

[git_branch]
symbol = "  "

# [hostname]
# ssh_only = true
# disabled = false

[cmd_duration]
format = "[  $duration ]($style)"
style = "fg:bright-white"

[character]
success_symbol = '[ ➜](bold green) '
error_symbol = '[ ✗](#E84D44) '

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "fg:bright-white"
format = '[ 󱑍 $time ]($style)'

[os]
disabled = false

[direnv]
disabled = false

[shell]
disabled = false
format = '[$shell]($style) '
style = 'bold yellow'
